### ISSUE TITLE
Second issue

### ISSUE THREAD

**Issue by punkyoon** [isivaprasad/C-Programmingclub#3]
hello @isivaprasad, i sent you a message included an algorithm problem.
happy coding day.

**Comment by isivaprasad** [comment]
Hello @punkyoon , That's good Job, However I found there are multiple Printf in the source code, you are suppose to be used a single printf, Please fix that. 😃

**Comment by punkyoon** [comment]
thanks, i got it.

**Comment by isivaprasad** [comment]
@punkyoon , I solved the problem you given, please check out and let me know if there is something issue remain . Thank you, 😃
